"""
StitchDraft logo mark: an S monogram rendered as a satin-stitch column,
generated by the same centre-line + perpendicular zigzag technique the
digitizing engine uses. The brand mark is literally engine output.
"""
import numpy as np
from scipy.interpolate import CubicSpline

# S centre-line control points (design grid 0..100)
ctrl = np.array([
    [78, 16],
    [58,  8],
    [36, 12],
    [28, 26],
    [38, 40],
    [58, 48],
    [70, 60],
    [64, 78],
    [44, 88],
    [22, 82],
])
t = np.linspace(0, 1, len(ctrl))
csx = CubicSpline(t, ctrl[:, 0])
csy = CubicSpline(t, ctrl[:, 1])

N = 96  # zigzag points (even)
ts = np.linspace(0, 1, N)
x, y = csx(ts), csy(ts)
dx, dy = csx(ts, 1), csy(ts, 1)
norm = np.hypot(dx, dy)
nx, ny = -dy / norm, dx / norm

# width profile: full through the body, tapered tips like a real column start
w = np.full(N, 9.0)
taper = 6
w[:taper] = np.linspace(4.5, 9.0, taper)
w[-taper:] = np.linspace(9.0, 4.5, taper)

sides = np.where(np.arange(N) % 2 == 0, 1.0, -1.0)
zx = x + nx * w / 2 * sides
zy = y + ny * w / 2 * sides

pts = " ".join(f"{a:.2f},{b:.2f}" for a, b in zip(zx, zy))

mark = f'''<g class="sd-mark">
  <polyline points="{pts}" fill="none" stroke="CURRENTCOLOR" stroke-width="2.6"
            stroke-linecap="round" stroke-linejoin="round"/>
</g>'''

with open("mark_points.txt", "w") as f:
    f.write(pts)
print("zigzag points written:", N)
